name: Sonar

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  shared:
    if: github.repository == 'vision-io/e2e-testing'
    uses: vision-io/ci-workflows/.github/workflows/sonar.yml@v1
    secrets: inherit

